class MRTStation {
  final String name;
  final double? latitude;
  final double? longitude;

  MRTStation({
    required this.name,
    this.latitude,
    this.longitude,
  });

  factory MRTStation.fromJson(Map<String, dynamic> json) {
    return MRTStation(
      name: json['name'],
      latitude: json['latitude']?.toDouble(),
      longitude: json['longitude']?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'latitude': latitude,
      'longitude': longitude,
    };
  }
}

// MRT Stations list matching the web project
const List<String> mrtStations = [
  "Admiralty MRT",
  "Aljunied MRT", 
  "Ang Mo Kio MRT",
  "Bartley MRT",
  "Bayfront MRT",
  "Beauty World MRT",
  "Bedok MRT",
  "Bedok North MRT",
  "Bedok Reservoir MRT",
  "Bencoolen MRT",
  "Bendemeer MRT",
  "Bishan MRT",
  "Boon Keng MRT",
  "Boon Lay MRT",
  "Botanic Gardens MRT",
  "Braddell MRT",
  "Bras Basah MRT",
  "Buangkok MRT",
  "Bugis MRT",
  "Bukit Batok MRT",
  "Bukit Brown MRT",
  "Bukit Gombak MRT",
  "Bukit Panjang MRT",
  "Buona Vista MRT",
  "Caldecott MRT",
  "Canberra MRT",
  "Cantonment MRT",
  "Cashew MRT",
  "Changi Airport MRT",
  "Chinatown MRT",
  "Chinese Garden MRT",
  "Choa Chu Kang MRT",
  "City Hall MRT",
  "Clementi MRT",
  "Commonwealth MRT",
  "Dakota MRT",
  "Dhoby Ghaut MRT",
  "Dover MRT",
  "Downtown MRT",
  "Esplanade MRT",
  "Eunos MRT",
  "Expo MRT",
  "Farrer Park MRT",
  "Farrer Road MRT",
  "Fort Canning MRT",
  "Geylang Bahru MRT",
  "Gul Circle MRT",
  "HarbourFront MRT",
  "Haw Par Villa MRT",
  "Hillview MRT",
  "Holland Village MRT",
  "Hougang MRT",
  "Jalan Besar MRT",
  "Joo Koon MRT",
  "Jurong East MRT",
  "Kaki Bukit MRT",
  "Kallang MRT",
  "Kembangan MRT",
  "Kent Ridge MRT",
  "Khatib MRT",
  "King Albert Park MRT",
  "Kovan MRT",
  "Kranji MRT",
  "Labrador Park MRT",
  "Lakeside MRT",
  "Lavender MRT",
  "Lorong Chuan MRT",
  "MacPherson MRT",
  "Marina Bay MRT",
  "Marina South Pier MRT",
  "Marsiling MRT",
  "Marymount MRT",
  "Mattar MRT",
  "Maxwell MRT",
  "Mountbatten MRT",
  "Newton MRT",
  "Nicoll Highway MRT",
  "Novena MRT",
  "one-north MRT",
  "Orchard MRT",
  "Outram Park MRT",
  "Pasir Panjang MRT",
  "Pasir Ris MRT",
  "Paya Lebar MRT",
  "Pioneer MRT",
  "Potong Pasir MRT",
  "Promenade MRT",
  "Punggol MRT",
  "Queenstown MRT",
  "Raffles Place MRT",
  "Redhill MRT",
  "Rochor MRT",
  "Sembawang MRT",
  "Sengkang MRT",
  "Serangoon MRT",
  "Shenton Way MRT",
  "Simei MRT",
  "Somerset MRT",
  "Stadium MRT",
  "Stevens MRT",
  "Tai Seng MRT",
  "Tampines MRT",
  "Tampines East MRT",
  "Tampines West MRT",
  "Tan Kah Kee MRT",
  "Tanah Merah MRT",
  "Tanjong Pagar MRT",
  "Telok Ayer MRT",
  "Telok Blangah MRT",
  "Tiong Bahru MRT",
  "Toa Payoh MRT",
  "Tuas Crescent MRT",
  "Tuas Link MRT",
  "Tuas West Road MRT",
  "Ubi MRT",
  "Upper Changi MRT",
  "Woodlands MRT",
  "Woodlands North MRT",
  "Woodlands South MRT",
  "Yew Tee MRT",
  "Yio Chu Kang MRT",
  "Yishun MRT",
];